#basically sweeps.yaml without slots hyperparameters
program: train.py
method: bayes
metric: 
    name: accuracy
    goal: minimize

description: 'easy-vqa-sweep-no-slots'

parameters: 

    #training hyperparameters
    epochs: 
        distribution: 'q_uniform'
        min: 20
        max: 40
        q: 5

    batch_size: 
        values: [32, 64, 128]
    
    learning_rate: 
        distribution: 'q_uniform'
        min: 0.0008
        max: 0.01 
        q: 0.0002

    #transformer hyperparamters: 
    nhead: #should be divisible by emb_dim 
       values: [4, 8] 
    
    tdim: 
        values: [256, 512]

    nlayers: 
        values: [ 3, 4]



    