program: train.py
method: bayes
metric: 
    name: accuracy
    goal: maximize

description: 'gqa-sweep'

parameters: 

    #training hyperparameters
    # epochs: 
    #     distribution: 'q_uniform'
    #     min: 20
    #     max: 35
    #     q: 5

    batch_size: 
        values: [32, 64, 128, 256]
    
    learning_rate: 
        distribution: 'q_uniform'
        min: 0.0007
        max: 0.01 
        q: 0.0002
    
    #slot attention hyperparameters: 
    simg: 
        distribution: 'q_uniform'    
        min: 5
        max: 30
        q: 5

    itersimg: 
        distribution: 'q_uniform'
        min: 3
        max: 10
        q: 2
      
    slotdimimg: 
        values: [256, 512, 768] 

    stext: 
        distribution: 'q_uniform'
        min: 5
        max: 30
        q: 5

    iterstext: 
        distribution: 'q_uniform'
        min: 2
        max: 10
        q: 2

    slotdimtext: 
        values: [256, 512, 768] 

    #transformer hyperparamters: 
    nhead: #should be divisible by emb_dim 
       values: [4, 8] 
    
    tdim: 
        values: [256, 512]

    nlayers: 
        values: [2, 3, 4]
    
    








